#! /bin/bash
wSize=5
timeout=.5
dropProb=.25
srvDelta=.05
cliDelta=.03
CWD=`pwd`
source /users/onl/.topology
echo "wSize=" $wSize " timeout=" $timeout " dropProb=" $dropProb
ssh $h7x1 "cd ${CWD}; java TestRdt h7x1 11313 ${wSize} ${timeout} debug \
    ${dropProb} ${srvDelta} .3 >srvOut1 &"
ssh $h4x2 "cd ${CWD}; java TestRdt h4x2 0 ${wSize} ${timeout} debug \
    ${dropProb} ${cliDelta} .3 h7x1 11313 >cliOut1"
echo "************** client report ****************"
cat cliOut1
sleep 5
echo "************** server report ****************"
cat srvOut1
